--!nonstrict

local InstructionIndex: { [string]: number } = { -- String index to number index list
	add            = 1,
	sub            = 2,
	mul            = 3,
	div            = 4,
	get            = 5,
	clear          = 6,
	move           = 7,
	set            = 8,
	cout           = 9,
	coutnl         = 10,
	coutnlrange    = 11,
	coutnlrangestr = 12,
	jmp            = 13,
	setpc          = 14,
	resetpc        = 15,
	halt           = 16,
	kill           = 17,
	testlt         = 18,
	testgt         = 19,
	testle         = 20,
	testge         = 21,
	testeq         = 22,
	call           = 23,
	["return"]     = 24,
};

local InstructionArgIndex: { [string]: number } = { -- String index to arg amount list
	add            = 3,
	sub            = 3,
	mul            = 3,
	div            = 3,
	get            = 2,
	clear          = 1,
	move           = 2,
	set            = 2,
	cout           = 1,
	coutnl         = 1,
	coutnlrange    = 2,
	coutnlrangestr = 2,
	jmp            = 1,
	setpc          = 1,
	resetpc        = 0,
	halt           = 1,
	kill           = 0,
	testlt         = 3,
	testgt         = 3,
	testle         = 3,
	testge         = 3,
	testeq         = 3,
	call           = 1,
	["return"]     = 2,
};

return table.freeze({
	InstructionIndex    = InstructionIndex    :: { [string]: number },
	InstructionArgIndex = InstructionArgIndex :: { [string]: number },
});
